spring.application.name=hms
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/test_hms
spring.datasource.username=postgres
spring.datasource.password=ash@Compunnel09





#spring.application.name=product_management
##spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/product_management_system
#spring.datasource.username=postgres
#spring.datasource.password=ash@Compunnel09
#
#
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data.locations=classpath:data.sql


#
#spring.application.name=product_management
##spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/product_management_system
#spring.datasource.username=postgres
#spring.datasource.password=ash@Compunnel09


spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.mode=never
spring.sql.init.data.locations=classpath:data.sql

#Spring security configs

#spring.security.user.name=ashish
#spring.security.user.password=pass

jwt.secretKey=supersecretpasswordoiasfjlkasjdfkasfjaksdlkfmkamfkalsmfasfmaskdlfmaskflmasklfm
