spring.application.name=hms
spring.application.name=JPA_Tutorial
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/hms
spring.datasource.username=postgres
spring.datasource.password=ash@Compunnel09



